[package]
name = "circuit_breaker"
version = "0.1.0"

[lib]
name = "circuit_breaker"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
rules_utils = { git = "https://github.com/ruleslabs/starknet-utils.git" }
starknet = ">=2.0.1"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
