name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCARB_VERSION: v0.5.1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Scarb binary
        uses: actions/cache@v3
        with:
          path: ~/.scarb
          key: scarb-${{ env.SCARB_VERSION }}-${{ runner.os }}
          restore-keys: scarb-${{ env.SCARB_VERSION }}-${{ runner.os }}

      - name: Scarb Setup
        run: |
          if [[ ! -f $HOME/.scarb/bin/scarb ]]; then
            wget https://github.com/software-mansion/scarb/releases/download/${{ env.SCARB_VERSION }}/scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
            mkdir $HOME/.scarb
            tar -xvzf scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz -C $HOME/.scarb --strip-components=1
          fi
          echo "$HOME/.scarb/bin" >> $GITHUB_PATH

      - name: Build the code 
        run: |
          scarb build

      - name: Test the code
        run: |
          scarb test